package reflections_and_annotation.section_06_spring;

import reflections_and_annotation.annotations_for_section5_and_section6.ComponentScan;
import reflections_and_annotation.annotations_for_section5_and_section6.Configuration;

@Configuration
@ComponentScan("reflections_and_annotation.annotations_for_section5_and_section6")
public class AppConfig {



}
